#!/bin/sh
#
# fcgi     Startup script for fcgi
#
# processname: redmine

# Source function library
. /etc/rc.d/init.d/functions

FCGI_DAEMON="/usr/bin/spawn-fcgi" 
FCGI_PROGRAM="/opt/redmine/public/dispatch.fcgi" 
FCGI_SOCKET="/tmp/redmine.sock" 
FCGI_PIDFILE="/var/run/redmine.pid"
RAILS_ENV="production"
RAILS_GEM_VERSION="2.0.0" # this should match the result of typing 'rails -v'
RAILS_ROOT="/opt/redmine"
RUBYLIB="/root/ruby-2.0.0-p0/lib/rubygems"
PATH=/usr/local/rvm/rubies/ruby-2.0.0-p0/bin:/usr/local/rvm/gems/ruby-2.0.0-p0@global/bin/:/opt/local/bin:/opt/local/sbin:/opt/local/var:$PATH
prog="redmine" 

export RAILS_ENV RAILS_GEM_VERSION RAILS_ROOT RUBYLIB PATH

RETVAL=0

start() {
        echo -n $"Starting $prog: "
		cd "/opt/redmine/public"
        daemon $FCGI_DAEMON -f $FCGI_PROGRAM -s $FCGI_SOCKET -P $FCGI_PIDFILE -u apache -g apache
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
        return $RETVAL
}

stop() {
        echo -n $"Stopping $prog: " 
        rm -f $FCGI_PIDFILE $FCGI_SOCKET
        killproc $FCGI_PROGRAM
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
        return $RETVAL
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        condrestart)
                if [ -f /var/lock/subsys/$prog ]; then
                        stop
                        start
                fi
                ;;
        status)
                status $lighttpd
                RETVAL=$?
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|condrestart|status}" 
                RETVAL=1
esac

exit $RETVAL